// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5EQIWhG1XqZaKYlksVR9z7zttsw7Xf2s',
    appId: '1:892979772545:web:5c81b2515dd66945412180',
    messagingSenderId: '892979772545',
    projectId: 'bigcart-66e11',
    authDomain: 'bigcart-66e11.firebaseapp.com',
    storageBucket: 'bigcart-66e11.firebasestorage.app',
    measurementId: 'G-8SQP6D0M3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUtipcsWfrEr3Smo149gCOBev9ojGKGrk',
    appId: '1:892979772545:android:55b29b48f76d813a412180',
    messagingSenderId: '892979772545',
    projectId: 'bigcart-66e11',
    storageBucket: 'bigcart-66e11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXePAQP4U7-ipj-YQ1gKfNjeIv7WCe72g',
    appId: '1:892979772545:ios:b05673f6afb615bc412180',
    messagingSenderId: '892979772545',
    projectId: 'bigcart-66e11',
    storageBucket: 'bigcart-66e11.firebasestorage.app',
    iosBundleId: 'com.example.bigCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXePAQP4U7-ipj-YQ1gKfNjeIv7WCe72g',
    appId: '1:892979772545:ios:b05673f6afb615bc412180',
    messagingSenderId: '892979772545',
    projectId: 'bigcart-66e11',
    storageBucket: 'bigcart-66e11.firebasestorage.app',
    iosBundleId: 'com.example.bigCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5EQIWhG1XqZaKYlksVR9z7zttsw7Xf2s',
    appId: '1:892979772545:web:e94b7cf533dfa69b412180',
    messagingSenderId: '892979772545',
    projectId: 'bigcart-66e11',
    authDomain: 'bigcart-66e11.firebaseapp.com',
    storageBucket: 'bigcart-66e11.firebasestorage.app',
    measurementId: 'G-7J1FM3KH4F',
  );
}
