import 'package:big_cart/firebase_options.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await seedProducts();
  runApp(const SizedBox());
}

Future<void> seedProducts() async {
  final col = FirebaseFirestore.instance.collection('products');

  final products = [
    // ===== Vegetables (13) =====
    {
      'name': 'Fresh Broccoli',
      'imageUrl': 'vegetables1',
      'category': 'Vegetables',
      'price': 2.50,
      'unit': '1 kg',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Fresh and crispy broccoli florets rich in vitamins.',
    },
    {
      'name': 'Fresh Carrot',
      'imageUrl': 'vegetables11',
      'category': 'Vegetables',
      'price': 1.99,
      'unit': '500 g',
      'isNew': true,
      'discount': 5,
      'inStock': true,
      'description': 'Organic carrots rich in vitamins and minerals.',
    },
    {
      'name': 'Fresh Tomato',
      'imageUrl': 'vegetables4',
      'category': 'Vegetables',
      'price': 3.00,
      'unit': '1 kg',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Juicy red tomatoes perfect for salads and cooking.',
    },
    {
      'name': 'Pumpkin',
      'imageUrl': 'vegetables13',
      'category': 'Vegetables',
      'price': 2.25,
      'unit': '500 g',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Fresh pumpkin packed with iron and nutrients.',
    },
    {
      'name': 'Sweet pumpkin',
      'imageUrl': 'vegetables12',
      'category': 'Vegetables',
      'price': 1.75,
      'unit': '500 g',
      'isNew': false,
      'discount': 10,
      'inStock': true,
      'description': 'Cool and crispy fresh Sweet pumpkin, great for vitamins.',
    },
    {
      'name': 'Fresh cauliflower',
      'imageUrl': 'vegetables7',
      'category': 'Vegetables',
      'price': 2.99,
      'unit': '500 g',
      'isNew': true,
      'discount': 0,
      'inStock': false,
      'description': 'Colorful capsicums full of vitamins and antioxidants.',
    },
    {
      'name': 'Fresh Onion',
      'imageUrl': 'vegetables9',
      'category': 'Vegetables',
      'price': 1.50,
      'unit': '1 kg',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Fresh onions essential for everyday cooking.',
    },
    {
      'name': 'Fresh Potato',
      'imageUrl': 'vegetables1',
      'category': 'Vegetables',
      'price': 2.00,
      'unit': '1 kg',
      'isNew': false,
      'discount': 5,
      'inStock': true,
      'description': 'Fresh potatoes, versatile and delicious for any dish.',
    },
    {
      'name': 'Sweet potato',
      'imageUrl': 'vegetables3',
      'category': 'Vegetables',
      'price': 3.25,
      'unit': '250 g',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Fresh sweet  and health benefits.',
    },
    {
      'name': 'Fresh Green chilli',
      'imageUrl': 'vegetables8',
      'category': 'Vegetables',
      'price': 2.75,
      'unit': '250 g',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Fresh green chilli cloves full of flavor and aroma.',
    },
    {
      'name': 'Fresh Brinjal',
      'imageUrl': 'vegetables2',
      'category': 'Vegetables',
      'price': 3.50,
      'unit': '1 kg',
      'isNew': true,
      'discount': 0,
      'inStock': true,
      'description': 'Fresh brinjal also sweet and full of nutrition',
    },
    {
      'name': 'Fresh Garlic',
      'imageUrl': 'vegetables10',
      'category': 'Vegetables',
      'price': 2.50,
      'unit': '500 g',
      'isNew': false,
      'discount': 15,
      'inStock': true,
      'description': 'Fresh Garlic rich in nutrients and fiber.',
    },
    {
      'name': 'Fresh Cabbage',
      'imageUrl': 'vegetables16',
      'category': 'Vegetables',
      'price': 1.99,
      'unit': '1 kg',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Fresh cabbage perfect for cooking and salads.',
    },

    // ===== Beverages (9) =====
    {
      'name': 'Sprite',
      'imageUrl': 'cold1',
      'category': 'Beverages',
      'price': 1.99,
      'unit': '1 liter',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Crisp lemon-lime soft drink with refreshing taste.',
    },
    {
      'name': 'Coca Cola',
      'imageUrl': 'cold2',
      'category': 'Beverages',
      'price': 3.50,
      'unit': '1 liter',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Classic fizzy cola drink loved worldwide.',
    },
    {
      'name': 'Diet coke',
      'imageUrl': 'cold3',
      'category': 'Beverages',
      'price': 3.99,
      'unit': '1 liter',
      'isNew': true,
      'discount': 0,
      'inStock': true,
      'description': 'Sugar-free cola with smooth refreshing flavor.',
    },
    {
      'name': 'Beer',
      'imageUrl': 'cold4',
      'category': 'Beverages',
      'price': 2.50,
      'unit': '500 ml',
      'isNew': false,
      'discount': 10,
      'inStock': true,
      'description': 'Chilled malt beverage with rich refreshing taste.',
    },
    {
      'name': 'Thumps Up',
      'imageUrl': 'cold5',
      'category': 'Beverages',
      'price': 5.99,
      'unit': '20 bags',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Strong sparkling cola with bold flavor.',
    },
    {
      'name': 'Red Bull',
      'imageUrl': 'cold6',
      'category': 'Beverages',
      'price': 1.99,
      'unit': '500 ml',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Energy drink that boosts energy and focus.',
    },
    {
      'name': 'Bubbly Apple Juice',
      'imageUrl': 'cold7',
      'category': 'Beverages',
      'price': 4.50,
      'unit': '1 liter',
      'isNew': true,
      'discount': 0,
      'inStock': true,
      'description': 'Fresh sparkling apple drink with fruity sweetness.',
    },
    {
      'name': 'Tuborg Beer',
      'imageUrl': 'cold8',
      'category': 'Beverages',
      'price': 3.99,
      'unit': '500 ml',
      'isNew': false,
      'discount': 15,
      'inStock': true,
      'description': 'Premium smooth beer with refreshing taste.',
    },
    {
      'name': 'Orange Beverage',
      'imageUrl': 'cold9',
      'category': 'Beverages',
      'price': 3.25,
      'unit': '1 liter',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Sweet citrus orange drink full of freshness.',
    },

    // ===== Edible Oil (7) =====
    {
      'name': 'Nut Oil',
      'imageUrl': 'edibleoil1',
      'category': 'Edible oil',
      'price': 12.99,
      'unit': '750 ml',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Healthy cooking oil made from natural nuts.',
    },
    {
      'name': 'Mustard Oil',
      'imageUrl': 'edibleoil2',
      'category': 'Edible oil',
      'price': 6.99,
      'unit': '1 liter',
      'isNew': false,
      'discount': 10,
      'inStock': true,
      'description': 'Pure cold-pressed mustard oil with rich aroma.',
    },
    {
      'name': 'Sunflower Oil',
      'imageUrl': 'edibleoil3',
      'category': 'Edible oil',
      'price': 9.99,
      'unit': '500 ml',
      'isNew': true,
      'discount': 0,
      'inStock': true,
      'description': 'Light healthy oil perfect for everyday cooking.',
    },
    {
      'name': 'Soyabin Oil',
      'imageUrl': 'edibleoil4',
      'category': 'Edible oil',
      'price': 5.99,
      'unit': '1 liter',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Refined soybean oil for regular cooking needs.',
    },
    {
      'name': 'Coconut Oil',
      'imageUrl': 'edibleoil5',
      'category': 'Edible oil',
      'price': 7.50,
      'unit': '2 liter',
      'isNew': false,
      'discount': 15,
      'inStock': true,
      'description': 'Natural coconut oil with rich tropical flavor.',
    },
    {
      'name': 'Olive Oil',
      'imageUrl': 'edibleoil6',
      'category': 'Edible oil',
      'price': 8.99,
      'unit': '1 liter',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Premium healthy oil ideal for cooking and salads.',
    },
    {
      'name': 'Rice Bran Oil',
      'imageUrl': 'edibleoil7',
      'category': 'Edible oil',
      'price': 10.99,
      'unit': '1 liter',
      'isNew': true,
      'discount': 0,
      'inStock': true,
      'description': 'Heart-friendly oil rich in nutrients and antioxidants.',
    },

    // ===== Grocery (10) =====
    {
      'name': 'Basmati Rice',
      'imageUrl': 'grocery1',
      'category': 'Grocery',
      'price': 8.99,
      'unit': '5 kg',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Premium quality basmati rice with long aromatic grains.',
    },
    {
      'name': 'Pasta',
      'imageUrl': 'grocery3',
      'category': 'Grocery',
      'price': 2.99,
      'unit': '500 g',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Italian style pasta made from durum wheat semolina.',
    },
    {
      'name': 'Cumin Seed',
      'imageUrl': 'grocery2',
      'category': 'Grocery',
      'price': 1.99,
      'unit': '400 g',
      'isNew': true,
      'discount': 0,
      'inStock': true,
      'description': 'Aromatic spice used to enhance food flavor.',
    },
    {
      'name': 'Noodles',
      'imageUrl': 'grocery4',
      'category': 'Grocery',
      'price': 4.50,
      'unit': '1 kg',
      'isNew': false,
      'discount': 10,
      'inStock': true,
      'description': 'Instant noodles for easy and fast cooking.',
    },
    {
      'name': 'Bread',
      'imageUrl': 'grocery5',
      'category': 'Grocery',
      'price': 2.50,
      'unit': '1 kg',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Soft fresh bread ideal for breakfast and snacks.',
    },
    {
      'name': 'Fruits Jam',
      'imageUrl': 'grocery6',
      'category': 'Grocery',
      'price': 0.99,
      'unit': '1 kg',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Sweet fruity jam spread for bread and desserts.',
    },
    {
      'name': 'Masur Dal',
      'imageUrl': 'grocery7',
      'category': 'Grocery',
      'price': 3.50,
      'unit': '2 kg',
      'isNew': false,
      'discount': 5,
      'inStock': true,
      'description': 'Nutritious red lentils rich in protein and taste.',
    },
    {
      'name': 'Moroccan Lentil',
      'imageUrl': 'grocery8',
      'category': 'Grocery',
      'price': 5.99,
      'unit': '1 kg',
      'isNew': true,
      'discount': 0,
      'inStock': true,
      'description': 'Flavorful premium lentils inspired by Moroccan cuisine.',
    },
    {
      'name': 'Garam Masala',
      'imageUrl': 'grocery9',
      'category': 'Grocery',
      'price': 4.99,
      'unit': '500 g',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Traditional spice blend for rich aromatic dishes.',
    },
    {
      'name': 'Ashirbad ATTA',
      'imageUrl': 'grocery10',
      'category': 'Grocery',
      'price': 7.99,
      'unit': '500 g',
      'isNew': false,
      'discount': 20,
      'inStock': true,
      'description': 'High-quality wheat flour for soft fresh chapati.',
    },

    // ===== Household (16) =====
    {
      'name': 'Detergent',
      'imageUrl': 'household1',
      'category': 'Household',
      'price': 2.99,
      'unit': '500 ml',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Powerful detergent for deep and effective cleaning.',
    },
    {
      'name': 'Baby Soap',
      'imageUrl': 'household2',
      'category': 'Household',
      'price': 2.50,
      'unit': '250 ml',
      'isNew': true,
      'discount': 0,
      'inStock': true,
      'description': 'Gentle soap specially made for baby skin.',
    },
    {
      'name': 'Fiama Men Soap',
      'imageUrl': 'household3',
      'category': 'Household',
      'price': 5.99,
      'unit': '400 ml',
      'isNew': false,
      'discount': 10,
      'inStock': true,
      'description': 'Refreshing soap designed for men’s skincare.',
    },
    {
      'name': 'Dove Soap',
      'imageUrl': 'household4',
      'category': 'Household',
      'price': 6.50,
      'unit': '400 ml',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Moisturizing beauty soap for soft smooth skin.',
    },
    {
      'name': 'Lux Soap',
      'imageUrl': 'household5',
      'category': 'Household',
      'price': 4.99,
      'unit': '500 ml',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Fragrant beauty soap with luxurious freshness.',
    },
    {
      'name': 'Dawn Dish Liquid',
      'imageUrl': 'household6',
      'category': 'Household',
      'price': 2.25,
      'unit': '150 g',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Strong dishwashing liquid that removes grease easily.',
    },
    {
      'name': 'Vim Liquid Green',
      'imageUrl': 'household7',
      'category': 'Household',
      'price': 3.99,
      'unit': '12 rolls',
      'isNew': false,
      'discount': 15,
      'inStock': true,
      'description': 'Effective dishwashing liquid with fresh lemon fragrance.',
    },
    {
      'name': 'Vim Liquid Lime',
      'imageUrl': 'household8',
      'category': 'Household',
      'price': 7.99,
      'unit': '1 kg',
      'isNew': true,
      'discount': 0,
      'inStock': true,
      'description':
          'Powerful lime dishwashing liquid for sparkling clean utensils.',
    },
    {
      'name': 'Nivea Men Facewash',
      'imageUrl': 'household9',
      'category': 'Household',
      'price': 4.50,
      'unit': '1 liter',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Refreshing face wash for deep cleaning and fresh skin.',
    },
    {
      'name': 'Body Gel',
      'imageUrl': 'household10',
      'category': 'Household',
      'price': 3.25,
      'unit': '500 ml',
      'isNew': false,
      'discount': 20,
      'inStock': true,
      'description': 'Smooth body cleansing gel with long lasting freshness.',
    },
    {
      'name': 'Shampoo',
      'imageUrl': 'household11',
      'category': 'Household',
      'price': 5.50,
      'unit': '300 ml',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Nourishing hair shampoo for clean and healthy hair.',
    },
    {
      'name': 'Colgate Toothpaste',
      'imageUrl': 'household12',
      'category': 'Household',
      'price': 3.75,
      'unit': '300 ml',
      'isNew': true,
      'discount': 0,
      'inStock': true,
      'description': 'Trusted toothpaste for strong teeth and fresh breath.',
    },
    {
      'name': 'Red Paste',
      'imageUrl': 'household13',
      'category': 'Household',
      'price': 2.99,
      'unit': '200 pcs',
      'isNew': false,
      'discount': 10,
      'inStock': true,
      'description':
          'Herbal toothpaste with natural ingredients for healthy gums.',
    },
    {
      'name': 'Ghari Detergent',
      'imageUrl': 'household14',
      'category': 'Household',
      'price': 2.50,
      'unit': '30 pcs',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Effective detergent powder for bright and clean clothes.',
    },
    {
      'name': 'Lifebuoy Soap',
      'imageUrl': 'household15',
      'category': 'Household',
      'price': 1.99,
      'unit': '3 pcs',
      'isNew': false,
      'discount': 5,
      'inStock': true,
      'description': 'Antibacterial soap for healthy and germ free skin.',
    },
    {
      'name': 'HB Shampoo',
      'imageUrl': 'household16',
      'category': 'Household',
      'price': 6.99,
      'unit': '1 pc',
      'isNew': false,
      'discount': 0,
      'inStock': true,
      'description': 'Gentle shampoo that keeps hair soft and shiny.',
    },
  ];

  int count = 0;
  for (final product in products) {
    await col.add(product);
    count++;
    print('✅ Added $count/${products.length}: ${product['name']}');
  }
  print('🎉 All $count products seeded successfully!');
}
